#!/bin/bash

# Load common definitions
. scripts/common.defs

(cd $EMACS/lisp/erc && find . -maxdepth 1 -mindepth 1 -type f -exec cp {} $OLDPWD \;)
cp $EMACS/etc/ERC-NEWS NEWS
cp $EMACS/doc/misc/erc.texi .
rm -f *.elc .cvsignore
