#!/bin/bash

# Load common definitions
. scripts/common.defs

IFS="
"

for i in $LISP; do
    cp $i $EMACS/lisp/erc
done

for i in $MAN; do
    cp $i $EMACS/doc/misc
done

for i in $IMAGES; do
    # Do nothing
    :
done

cp $NEWS $EMACS/etc/ERC-NEWS
